stages:
  - build
  - test

variables:
  DOTNET_VERSION: "7.0"  # Specify the .NET SDK version

# Cache dependencies for faster builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.nuget/packages/

# Build stage
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
  script:
    - dotnet restore CIprj_April2024.sln  # Restore dependencies
    - dotnet build CIprj_April2024.sln --configuration Release  # Build in Release mode
  artifacts:
    paths:
      - bin/  # Save the build output to use in later stages

# Test stage
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
  dependencies:
    - build
  script:
    - dotnet test CIprj_April2024.sln --logger:trx --results-directory TestResults  # Run tests and log results
  artifacts:
    when: always
    paths:
      - TestResults/*.trx  # Save the test results as artifacts
  allow_failure: false
