variables:
  PROJECT_CI: "CIprj_April2024"

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - 'echo "building..."'
    - '"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "D:\CSharp_Projects\CIprj_April2024\CIprj_April2024.sln"'
  artifacts:
    untracked: true

test_job:
  stage: test
  script:
    - 'echo "Testing..."'
    - '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\MSTest.exe" /testcontainer:"D:\CSharp_Projects\CIprj_April2024\CIprj_April2024\bin\Debug\net6.0-windows\CIprj_April2024.dll"'
  dependencies:
    - build_job
