stages
  - build
  - test
  - deploy

variables
  # Set the version of .NET SDK to use
  DOTNET_VERSION '7.0'  # Update this if you're using a different .NET version

# Install .NET SDK and run build tasks
before_script
  - 'echo Installing .NET SDK...'
  - 'curl -sSL httpsdotnet.microsoft.comdownloaddotnetsdk  bash'

# Define the build job
build
  stage build
  script
    - 'echo Restoring dependencies...'
    - 'dotnet restore'
    - 'echo Building the project...'
    - 'dotnet build --configuration Release'
  artifacts
    paths
      - binReleasenet7.0  # Adjust the path depending on the .NET version

# Define the test job (if you have unit tests)
test
  stage test
  script
    - 'echo Running tests...'
    - 'dotnet test --configuration Release'
  dependencies
    - build

# Define the deployment job (optional, for deploying to a server or container registry)
deploy
  stage deploy
  script
    - 'echo Deploying project...'
    - 'dotnet publish --configuration Release --output publish'
  dependencies
    - build
  only
    - main  # Run deployment only for the main branch (adjust if necessary)
