variables:
  PROJECT_CI: "CIprj_April2024"
before_script:
  - '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\NuGet restore CIprj_April2024.sln"'

stages:
  - build
  - test

variables:
  DOTNET_VERSION: "7.0"  # Specify the .NET SDK version

# Cache dependencies for faster builds
cache:
  paths:
    - ~/.nuget/packages/

# Build stage
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
  script:
    - 'echo "Building..."'
  except:
    - tags

# Test stage
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}
  dependencies:
    - build
  script:
    - 'echo "Testing..."'
