name: .NET Build & Test

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PR creation or update to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out the repository code

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Specify the .NET version you are using

    - name: Restore dependencies
      run: dotnet restore  # Restores the NuGet dependencies

    - name: Build the project
      run: dotnet build --configuration Release  # Builds the project in Release mode

    - name: Run tests
      run: dotnet test --configuration Release  # Runs the tests using MSTest

    - name: Publish results
      if: always()
      run: |
        # Publishing test results to GitHub Actions
        if [ -f TestResults/*.xml ]; then
          cp TestResults/*.xml ./test-results/
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results  # Upload test results as an artifact for review
